
import React, { useEffect, useState } from 'react';
import { OrderData } from '../types';
import { generateFormalConfirmation } from '../services/geminiService';
import { CheckCircle, Mail, ArrowLeft, FileText, Send, Download, FileDown } from 'lucide-react';
import { jsPDF } from 'jspdf';

interface SuccessViewProps {
  order: OrderData;
  onReset: () => void;
}

export const SuccessView: React.FC<SuccessViewProps> = ({ order, onReset }) => {
  const [aiMessage, setAiMessage] = useState<string>('メッセージを作成中...');
  const [isGenerating, setIsGenerating] = useState(true);
  const [isSent, setIsSent] = useState(false);

  useEffect(() => {
    generateFormalConfirmation(order).then(setAiMessage);
    
    // Simulate PDF generation and email sending
    const timer = setTimeout(() => {
      setIsGenerating(false);
      setTimeout(() => setIsSent(true), 1500);
    }, 2000);

    return () => clearTimeout(timer);
  }, [order]);

  const downloadPDF = () => {
    const doc = new jsPDF();
    const title = 'Order Confirmation / ご注文内容確認書';
    
    doc.setFontSize(22);
    doc.setTextColor(219, 39, 119); // Pink-600
    doc.text(title, 20, 25);
    
    doc.setDrawColor(200, 200, 200);
    doc.line(20, 30, 190, 30);
    
    doc.setFontSize(12);
    doc.setTextColor(80, 80, 80);
    
    let y = 45;
    const addRow = (label: string, value: string) => {
      doc.setFont("helvetica", "bold");
      doc.text(`${label}:`, 20, y);
      doc.setFont("helvetica", "normal");
      doc.text(value, 70, y);
      y += 10;
    };

    const formattedWake = order.wakeDateTime === 'なし' ? 'なし' : order.wakeDateTime.replace('T', ' ');
    const formattedFuneral = order.funeralDateTime.replace('T', ' ');

    addRow('Family Name', `${order.familyName} Family`);
    addRow('Flower Type', order.flowerType);
    addRow('Location', order.funeralLocation);
    addRow('Wake Date/Time', formattedWake);
    addRow('Funeral Date/Time', formattedFuneral);
    
    y += 5;
    doc.line(20, y, 190, y);
    y += 10;
    
    addRow('Contact Name', order.contactName);
    addRow('Email', order.email);
    addRow('Phone', order.phoneNumber);
    addRow('Address', `${order.zipCode} ${order.address}`);
    addRow('Transfer Name', order.transferName);
    addRow('Placard Name', order.placardName);
    
    y += 20;
    doc.setFontSize(10);
    doc.setTextColor(150, 150, 150);
    doc.text('Generated by OKURI Flower Order System', 20, y);
    
    doc.save(`order_${order.familyName}_${new Date().getTime()}.pdf`);
  };

  return (
    <div className="glass-card p-6 md:p-8 rounded-3xl shadow-xl text-center space-y-8 animate-in zoom-in duration-500">
      <div className="flex justify-center">
        <div className="bg-green-100 p-4 rounded-full text-green-600 relative">
          <CheckCircle size={48} />
          {isSent && (
            <div className="absolute -top-1 -right-1 bg-pink-500 text-white rounded-full p-1 animate-bounce">
              <Mail size={16} />
            </div>
          )}
        </div>
      </div>

      <div>
        <h2 className="text-2xl font-bold text-gray-800">ご注文ありがとうございます</h2>
        <p className="text-gray-500 mt-2 font-serif italic text-sm">
          {isSent ? "内容をPDF化し、管理者に送信いたしました。" : "注文を処理しています..."}
        </p>
      </div>

      {/* PDF Status Card */}
      <div className="bg-gray-50 rounded-2xl p-6 border border-gray-100 text-left">
        <div className="flex items-center justify-between mb-4">
          <div className="flex items-center gap-2">
            <FileText className="text-gray-400" size={20} />
            <span className="text-sm font-bold text-gray-600">注文内容PDF</span>
          </div>
          {isGenerating ? (
            <span className="text-xs text-pink-600 animate-pulse font-bold">作成中...</span>
          ) : (
            <span className="text-xs text-green-600 font-bold flex items-center gap-1">
              <CheckCircle size={12} /> 作成完了
            </span>
          )}
        </div>
        
        <div className="flex items-center gap-3 py-3 px-4 bg-white rounded-xl border border-dashed border-gray-200">
          <Send className={isSent ? "text-green-500" : "text-gray-300 animate-pulse"} size={18} />
          <p className="text-xs text-gray-500">
            {isSent 
              ? "管理者メールアドレスへのPDF送信が完了しました。" 
              : "PDFを生成し、管理者へ送信しています..."}
          </p>
        </div>
      </div>

      <div className="bg-pink-50/50 p-6 rounded-2xl border border-pink-100 text-left space-y-4">
        <div className="flex items-start gap-3">
          <Mail className="text-pink-600 mt-1 flex-shrink-0" size={20} />
          <div>
            <p className="text-[10px] font-bold text-pink-600 uppercase tracking-widest mb-1">Confirmation Message</p>
            <p className="text-gray-700 font-medium font-serif leading-relaxed italic">
              "{aiMessage}"
            </p>
          </div>
        </div>
      </div>

      <div className="space-y-3 pt-4">
        <button 
          onClick={downloadPDF}
          disabled={isGenerating}
          className="w-full py-4 rounded-xl bg-pink-600 text-white font-bold hover:bg-pink-700 transition-all flex items-center justify-center gap-2 shadow-lg shadow-pink-100 disabled:bg-gray-300 disabled:shadow-none"
        >
          <FileDown size={20} />
          注文内容をPDFで保存する
        </button>

        <button 
          onClick={onReset}
          className="w-full py-4 rounded-xl border-2 border-pink-600 text-pink-600 font-bold hover:bg-pink-50 transition-all flex items-center justify-center gap-2"
        >
          <ArrowLeft size={20} />
          トップへ戻る
        </button>
      </div>

      <p className="text-[10px] text-gray-400">
        ※このデモでは実際にメールは送信されませんが、PDF生成機能は利用可能です。
      </p>
    </div>
  );
};
